// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyPortal.API.Models;

#nullable disable

namespace PolicyPortal.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703094655_AddCreatedDateToPolicyAssignment")]
    partial class AddCreatedDateToPolicyAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyPortal.API.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId")
                        .HasName("PK__AuditLog__A17F2398BD709E5C");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B44D65D95");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E0F224CEB3")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BED52E114A3");

                    b.HasIndex(new[] { "DepartmentName" }, "UQ__Departme__D949CC34EE78AD1A")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E123D654C10");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<string>("BlobPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PolicyId")
                        .HasName("PK__Policies__2E1339A4121519A1");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyAcknowledgment", b =>
                {
                    b.Property<int>("AcknowledgmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcknowledgmentId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("ConsentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AcknowledgmentId")
                        .HasName("PK__PolicyAc__9342B48A95A9F4D1");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicyAcknowledgments");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("AssignedToDepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId")
                        .HasName("PK__PolicyAs__32499E773D21CCFD");

                    b.HasIndex("AssignedToDepartmentId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("VersionId");

                    b.ToTable("PolicyAssignments");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicySignature", b =>
                {
                    b.Property<int>("SignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SignatureId"));

                    b.Property<int>("AcknowledgmentId")
                        .HasColumnType("int");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("SignatureHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SignedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SignatureId")
                        .HasName("PK__PolicySi__3DCA57A99E3581AA");

                    b.HasIndex("AcknowledgmentId");

                    b.HasIndex("SignedBy");

                    b.ToTable("PolicySignatures");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyVersion", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VersionId")
                        .HasName("PK__PolicyVe__16C6400F621CBFDE");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "PolicyId", "VersionNumber" }, "UQ_Policy_Version")
                        .IsUnique();

                    b.ToTable("PolicyVersions");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.ReportExport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("GeneratedBy")
                        .HasColumnType("int");

                    b.HasKey("ReportId")
                        .HasName("PK__ReportEx__D5BD4805E0EE2C33");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("ReportExports");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1A4351B01C");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B616025AAA37C")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AzureObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C65FDFD63");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053428CA2F81")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.AuditLog", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Audit_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Notification", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Policy", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.Category", "Category")
                        .WithMany("Policies")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Policies_Category");

                    b.HasOne("PolicyPortal.API.Models.User", "CreatedByNavigation")
                        .WithMany("Policies")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Policies_User");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyAcknowledgment", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.PolicyAssignment", "Assignment")
                        .WithMany("PolicyAcknowledgments")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Ack_Assignment");

                    b.HasOne("PolicyPortal.API.Models.User", "User")
                        .WithMany("PolicyAcknowledgments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Ack_User");

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyAssignment", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.Department", "AssignedToDepartment")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("AssignedToDepartmentId")
                        .HasConstraintName("FK_Assign_Department");

                    b.HasOne("PolicyPortal.API.Models.User", "AssignedToUser")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("AssignedToUserId")
                        .HasConstraintName("FK_Assign_User");

                    b.HasOne("PolicyPortal.API.Models.Policy", "Policy")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Policy");

                    b.HasOne("PolicyPortal.API.Models.PolicyVersion", "Version")
                        .WithMany("PolicyAssignments")
                        .HasForeignKey("VersionId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Version");

                    b.Navigation("AssignedToDepartment");

                    b.Navigation("AssignedToUser");

                    b.Navigation("Policy");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicySignature", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.PolicyAcknowledgment", "Acknowledgment")
                        .WithMany("PolicySignatures")
                        .HasForeignKey("AcknowledgmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Sign_Ack");

                    b.HasOne("PolicyPortal.API.Models.User", "SignedByNavigation")
                        .WithMany("PolicySignatures")
                        .HasForeignKey("SignedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Sign_User");

                    b.Navigation("Acknowledgment");

                    b.Navigation("SignedByNavigation");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyVersion", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.User", "CreatedByNavigation")
                        .WithMany("PolicyVersions")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Versions_User");

                    b.HasOne("PolicyPortal.API.Models.Policy", "Policy")
                        .WithMany("PolicyVersions")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK_Versions_Policy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.ReportExport", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.User", "GeneratedByNavigation")
                        .WithMany("ReportExports")
                        .HasForeignKey("GeneratedBy")
                        .HasConstraintName("FK_Report_User");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.User", b =>
                {
                    b.HasOne("PolicyPortal.API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Users_Department");

                    b.HasOne("PolicyPortal.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Users_Role");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Category", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Department", b =>
                {
                    b.Navigation("PolicyAssignments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Policy", b =>
                {
                    b.Navigation("PolicyAssignments");

                    b.Navigation("PolicyVersions");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyAcknowledgment", b =>
                {
                    b.Navigation("PolicySignatures");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyAssignment", b =>
                {
                    b.Navigation("PolicyAcknowledgments");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.PolicyVersion", b =>
                {
                    b.Navigation("PolicyAssignments");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PolicyPortal.API.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Policies");

                    b.Navigation("PolicyAcknowledgments");

                    b.Navigation("PolicyAssignments");

                    b.Navigation("PolicySignatures");

                    b.Navigation("PolicyVersions");

                    b.Navigation("ReportExports");
                });
#pragma warning restore 612, 618
        }
    }
}
